package com.pigsense.anticheat.util;

import com.github.retrooper.packetevents.wrapper.play.client.WrapperPlayClientPlayerFlying;
import com.pigsense.anticheat.data.PlayerData;

/*
@mfinikov:
that part of code was generated by chatgpt,
so if you know the way to improve it
please create an issue on the github repo
*/

public class MovementUtil {

    public static void updateMovement(WrapperPlayClientPlayerFlying flying, PlayerData data) {

        data.lastX = data.x;
        data.lastY = data.y;
        data.lastZ = data.z;

        data.lastOnGround = data.onGround;

        if (flying.hasPositionChanged()) {
            data.x = flying.getLocation().getX();
            data.y = flying.getLocation().getY();
            data.z = flying.getLocation().getZ();
        }

        data.deltaX = data.x - data.lastX;
        data.deltaY = data.y - data.lastY;
        data.deltaZ = data.z - data.lastZ;

        data.onGround = flying.isOnGround();

        if (data.onGround) {
            data.groundTicks++;
            data.airTicks = 0;
        } else {
            data.airTicks++;
            data.groundTicks = 0;
        }

        data.lastYaw = data.yaw;
        data.lastPitch = data.pitch;

        if (flying.hasRotationChanged()) {
            data.yaw = flying.getLocation().getYaw();
            data.pitch = flying.getLocation().getPitch();
        }

        data.deltaYaw = Math.abs(data.yaw - data.lastYaw);
        data.deltaPitch = Math.abs(data.pitch - data.lastPitch);
    }
}
